### ISSUE TITLE
In settings and github description only "discharge" is mentioned in relation to the rate bar

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#11]
As said [here](https://github.com/lonelytransistor/kde_batterybar/issues/1#issuecomment-1329427161), the rate bar shows not only the discharge, but also the charge rate per hour.

> It shows the charging rate. I.e. what amount of battery will be charged within the hour.

That should be added in the description of the auxiliary bar, here: https://github.com/lonelytransistor/kde_batterybar#usage

Also, in rate bar settings, "discharge" is the only term used to discuss color and opacity. "Charge/discharge" should be used instead.

**Comment by lonelytransistor** [comment]
Ok, changed the description to a clearer one.
