### ISSUE TITLE
Changing bar position greatly increases its thickness 

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#13]
This doesn't happen with any change, but it happens for example, in this configuration, with the two very thin (2 pixel) parallel bars (rate is below):

![image](https://user-images.githubusercontent.com/3447868/207049533-39787fe6-b9bb-4e41-b810-80966e7971a6.png)

if I change the position of the discharging rate bar (the one below) from bottom left to top left, so that the two are superposed, the rate bar changes its size too:

![image](https://user-images.githubusercontent.com/3447868/207050300-b82ef2a2-7bac-4067-bf1c-59048dfd8668.png)

This can be fixed by changing the thickness from 2 to 3, saving, and again from 3 to 2 - and saving again.

**Comment by lonelytransistor** [comment]
Fixed.
