### ISSUE TITLE
Connecting or disconnecting resets rate bar thickness to full

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#14]
Similar to the previously reported bug  https://github.com/lonelytransistor/kde_batterybar/issues/13, but triggered by connecting or disconnecting the power cable. 

(widget left of the system tray, both bars have 2-pixel thickness, the upper bar is the charge)

Charging it looks like so:

![image](https://user-images.githubusercontent.com/3447868/207057572-5ca9aecc-7ee7-465e-bfc8-a7b8a04c5857.png)

and discharging like so:

![image](https://user-images.githubusercontent.com/3447868/207058253-7f7fb822-1cc6-4160-91f6-137e54606d38.png)

although the settings look like so:

![image](https://user-images.githubusercontent.com/3447868/207057806-aaf02ee0-3896-4c33-808d-996abd19ca2e.png)

(Like the other problem, it's fixed by changing the thickness from 2 to 3, saving, and again from 3 to 2 - and saving again.)

**Comment by cipricus** [comment]
It might be the same bug as https://github.com/lonelytransistor/kde_batterybar/issues/13, because it can be reduced to the behavior triggered by changing the bar position: my setting says in fact that the rate bar should be top left when discharging and bottom left when charging. So, I can fix this by simply choosing a setting where the rate bar has the same position when charging and discharging.

**Comment by lonelytransistor** [comment]
Fixed.
