### ISSUE TITLE
The rate bar is too long?

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#15]
The widget is situated on a top plasma panel, like so:

![image](https://user-images.githubusercontent.com/3447868/207062040-981d5e9b-a2f7-4771-aae7-be58c68a565b.png)

But although sometimes the charging rate bar fills all the space to the right, in other cases it goes far to the left.

![image](https://user-images.githubusercontent.com/3447868/207062349-51e8605b-2fc2-4d1e-90df-00595889f472.png)

I think that is because I have set the charging rate bar to be situated "bottom right", so that it extends to the left now. But is that going so much to the left beyond the widget position expected? I was under the impression that the bars only go to the right of the widget container, and never to the left of it, because if I put the widget at the extreme right, like so

![image](https://user-images.githubusercontent.com/3447868/207063906-3ac367f6-211f-4e8d-ab59-8197edaade6b.png)

then both bars are squeezed to the right, even if I set them both to the right

![image](https://user-images.githubusercontent.com/3447868/207064127-6efd176e-d754-453b-8c6d-d792d38da103.png)

Is that normal?

**Comment by lonelytransistor** [comment]
Fixed
