### ISSUE TITLE
Question: what are rate segments?

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#16]
I have this setting for the purpose of this question:

![image](https://user-images.githubusercontent.com/3447868/207075521-707f7256-8cc0-4496-a0a6-9c3927f7c6c4.png)

And now the rate bar shows a lot of segments.

![image](https://user-images.githubusercontent.com/3447868/207075698-4a9d3864-7b3e-4f69-8344-fb531f4a992d.png)

What do they represent?

**Comment by lonelytransistor** [comment]
Added an explanation.
