### ISSUE TITLE
Main bar is full all the time

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#2]
It should be like described:

>    main bar (green by default) - fills the screen based on the percentage of power left in the battery,

But the green bar has filled the screen completely, while the battery is below half:

![image](https://user-images.githubusercontent.com/3447868/204323104-9b47fc4a-70b7-4341-9477-bae2b783efa4.png)

and after a while as the battery drains the main bar stays full.

**Comment by cipricus** [comment]
Oh, it has to be put at the beginning of the panel!

**Comment by cipricus** [comment]
Oh, it has to be put at the beginning of the panel!

**Comment by lonelytransistor** [comment]
Now the applet can be placed anywhere.

**Comment by cipricus** [comment]
> Now the applet can be placed anywhere.

Can the updated version be installed from "Add widgets" or just github?

**Comment by lonelytransistor** [comment]
All versions can be downloaded from the KDE Store - I upload them everytime I build a new version.
