### ISSUE TITLE
No charging-related animations

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#4]
- when the battery is charging the main bar slowly breathes once in a while: I have set that very low to be able to test it works, I see nothing
- whenever the charger is disconnected several bubbles will be shown to escape the main bar to the right: no bubbles
- when the charger is connected a swift bright flash will travel through the main bar from left to right: that should be hard to miss, but I don't see it.

The panel is to the top:

![image](https://user-images.githubusercontent.com/3447868/204334692-90a360dc-6d0e-4543-b4f3-9b5192d69339.png)

Could it be because of my hardware? I'm on a macbook.

**Comment by lonelytransistor** [comment]
Confirmed and recreated. There is a regression when restructuring the files.

**Comment by lonelytransistor** [comment]
Should be fixed in the 1.0 version. Please try now and see if it works.

**Comment by cipricus** [comment]
It works now.
