### ISSUE TITLE
The widget icon shouldn't take space on the panel outside edit mode

### ISSUE THREAD

**Issue by cipricus** [lonelytransistor/kde_batterybar#8]
The widget has a visible icon in edit mode, but the space that icon takes on panel when it is invisible (in normal mode, by contrast to edit mode), is still visible.

See in this image below how another widget (Transparent panel button)  that has a similar button visible only in edit mode fills no space outside edit mode, while this widget keeps taking space on the panel:

![image](https://user-images.githubusercontent.com/3447868/205490556-f1a677d7-9b22-4c40-bb99-79746340c8b3.png)

![image](https://user-images.githubusercontent.com/3447868/205490611-56a969ab-be49-4913-bdcd-40058614c4bc.png)

**Comment by cipricus** [comment]
I think that I understand now that the container size is referring also to that empty space. I don't understand what's the point in having an adjustable size of an icon that is visible only in edit mode, but that's it: reducing the "container" size to minimum, the size of that empty space is reduced too.

![image](https://user-images.githubusercontent.com/3447868/205496543-bdad8368-7e21-4a33-88ad-ec32d0cbcfe2.png)

**Comment by lonelytransistor** [comment]
Container size changes the container's size in normal mode. This is explained in detail in the widget's description at the KDE store and here in the README.

This is an old version looking at the screenshot. Please do not open issues regarding old versions of the software.

**Comment by cipricus** [comment]
Sorry, I didn't realize it was so quickly updated. Great work!
